### ISSUE TITLE
Tela de cadastro de médico não permite inserção de preferência de intervalo

### ISSUE THREAD

**Issue by danilo-p** [danilo-p/pm-clinicasaracura#16]
De acordo com a especificação, o médico pode escolher o seu tempo de intervalo.

> Cada médico tem sua própria agenda na cooperativa contendo seus dados pessoais, suas
> especialidades e a disponibilidade de horário. Um médico atende durante 6 horas contínuas entre
> 7h e 20h, três vezes por semana. **O intervalo de cada consulta pode ser de 15, 20 ou 30 minutos
> conforme escolha do médico.**

**Comment by anallr** [comment]
Além disso, ele deverá indicar também o horário em que atende (sendo 6h contínuas entre 7h e 20h) e os dias da semana.
